### ISSUE TITLE
DCA Study guide query

### ISSUE THREAD

**Issue by ravenkh** [Evalle/DCA#37]
Hi guys,
is this the updated guide for the DCA exam? https://github.com/Evalle/DCA#useful-links
It looks published in August 2020
has anyone taken this exam recently?
thanks!

**Comment by Evalle** [comment]
Hi @ravenkh, let me answer your questions:
> is this the updated guide for the DCA exam? https://github.com/Evalle/DCA#useful-links

There is none, the latest has been published on the official website in 2020 and hasn't been updated since. I asked the same question Mirantis representative directly ans the answer was the same - the latest guide is the one from 2020. 

> has anyone taken this exam recently?

I haven't but I can suggest to ask the same on reddit or StackOverflow 

Thanks!
